[package]
name = "pubport"
version = "0.1.0"
edition = "2021"

[dependencies]
# Bitcoin
bdk_wallet = { version = "1.0.0-beta.4", features = [] }
bitcoin = "0.32"

# errors
thiserror = "1.0"

# logging
log = "0.4"

# serde
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
